### ISSUE TITLE
Docker Container Once Stopped will not Run again!!!

### ISSUE THREAD

**Issue by egooner** [JulianPrieber/llc-docker#27]
Having broken my littlelink container trying to get it to upgrade I started again again from scratch with a new container, pull and new volume ... determined to make this work!!

Latest pull using v3.0.3 image sha256:6ce23bffd4cd5b17dcdfb09cdc7943ff4c75637da2c882f0671ac0cada82c111

I found the same issue that I saw before with the following messages appearing after a docker instance is stopped and restarted.

```
Updating Configuration: Apache Base (/etc/apache2/httpd.conf)
Updating Configuration: Apache SSL  (/etc/apache2/conf.d/ssl.conf)
Updating Configuration: PHP         (/etc/php8/php.ini)
Updating Configuration: Complete
Running Apache
AH00526: Syntax error on line 337 of /etc/apache2/httpd.conf:
Invalid command 'io', perhaps misspelled or defined by a module not included in the server configuration
```

Before restarting I extracted the HTTPD.CONF as I was expecting the problem and it looked like this at the offending location
```
    BrowserMatchNoCase ^healthcheck nolog
    CustomLog "logs/access.log" combinedio env=!nolog
</IfModule>
```

I then dumped the container as it was not running/runable and I had no persistent storage for /etc/apache2 setup to extract the httpd.conf file

```
    BrowserMatchNoCase ^healthcheck nolog
    BrowserMatchNoCase ^healthcheck nolog
    CustomLog "logs/access.log" combinedio env=!nolog
io env=!nolog
</IfModule>
``` 

I also ran a diff and these were the only differences!! (All empty lines stripped out from the above extracts)

Note that if I try to restart the httpd.conf is modified again and this time

```
    BrowserMatchNoCase ^healthcheck nolog
    BrowserMatchNoCase ^healthcheck nolog
    BrowserMatchNoCase ^healthcheck nolog
    CustomLog "logs/access.log" combinedio env=!nolog
io env=!nolog
io env=!nolog

</IfModule>
```

**Comment by JulianPrieber** [comment]
Hey @egooner I just confirmed this is indeed a bug.

More precisely, if you only mapped port 80 to something else, the docker will fail after stopping.
An easy way of fixing this should be just to map port 443 to something. You don't have to actually use it.

This did not happen in previous versions.
I was able to trace the bug to this commit https://github.com/JulianPrieber/llc-docker/commit/4f7443dc547cdab82a5bd9d609cd3b252a99cba1.

I will revert this for now, and I will release a version that includes this shortly.

**Comment by JulianPrieber** [comment]
@STaRDoGG I had to revert your commit https://github.com/JulianPrieber/llc-docker/commit/4f7443dc547cdab82a5bd9d609cd3b252a99cba1 due to reasons stated [above](
https://github.com/JulianPrieber/llc-docker/issues/27#issuecomment-1326459578).

I'm not sure what's exactly causing this. Could you investigate?

**Comment by egooner** [comment]
OK - so are you referring to mapping port 80 and 443 for use outside of the container - 
```
    --publish 80:80 \
    --publish 443:443 \
```

I do not map them at all as the Proxy is on the same logical network it communicates directly with it and by not exposing ports it means you cannot reach the backend without going through the proxy.  Are you saying I should publish the ports as a work around?

**Comment by JulianPrieber** [comment]
> Are you saying I should publish the ports as a work around?

Yes.

Alternatively, you can just wait for the temporary fix that should come out in about 15 minutes.

**Comment by egooner** [comment]
Correction - on the last one (I am using Portainer) I did have ports published

**Comment by JulianPrieber** [comment]
It took a bit, but this should do it for now: https://hub.docker.com/layers/julianprieber/littlelink-custom/latest/images/sha256-03c785dd9f0a53cc0fa4c48c6b34b38c03c49870815e319ddbb5b039a3e42133?context=explore

On my portainer instance, this is working fine now.

**Comment by egooner** [comment]
Great - many thanks - restart now works OK from a new container - I hope that this is OK I saved and copied over my database and it seems to have remembered the critical things.
I do still have an issue with the HTTPS mod but will raise that as a separate issue to avoid confusion

**Comment by STaRDoGG** [comment]
> @STaRDoGG I had to revert your commit [4f7443d](https://github.com/JulianPrieber/llc-docker/commit/4f7443dc547cdab82a5bd9d609cd3b252a99cba1) due to reasons stated [above](https://github.com/JulianPrieber/llc-docker/issues/27#issuecomment-1326459578).
> 
> I'm not sure what's exactly causing this. Could you investigate?

Just at a super-quick lookover, I'm suspecting the search & replace is just getting screwed up somewhere near here, in `docker-entrypoint.sh`:

```
sed -i 's#CustomLog .* combined#BrowserMatchNoCase ^healthcheck nolog\n\n CustomLog "logs/access.log" combinedio env=!nolog\n#g' /etc/apache2/httpd.conf
```

Not sure what changed though that would have caused that; maybe the bump to the latest alpine or something. Probably just a matter of editing that S&R though. I can't really investigate for the next few days at least, though.

**Comment by STaRDoGG** [comment]
Looking at things right now, none of the php8 packages are availing in Alpine 3.17: https://pkgs.alpinelinux.org/packages?name=php8-*&branch=v3.17&repo=&arch=&maintainer=

**Comment by JulianPrieber** [comment]
For now, I will continue using Alpine 3.16

**Comment by STaRDoGG** [comment]
Seems like I got it. You guys wanna give this container a test? No other changes needed:

jscottelblein/llc-docker:latest

Log: 

![image](https://user-images.githubusercontent.com/1524526/206581532-f96e4398-470c-41cf-af3d-f2866668b76e.png)

Healthcheck:

![image](https://user-images.githubusercontent.com/1524526/206581552-bfa7c881-855b-468c-a4e1-2ec97461aace.png)

FYI, the very first error I had while trying to resolve the issue was this:

![image](https://user-images.githubusercontent.com/1524526/206582294-b3c06404-35df-4b33-8459-a9660038dea2.png)

And clicking the Run Migrations button fixed that.

**Comment by STaRDoGG** [comment]
Also just an added note: the error in the OP was due to multiple runs of `docker-entrypoint.sh` on the same `httpd.conf` file. I fixed this so it won't matter if it's gets run multiple times on the same `.conf` again.

**Comment by JulianPrieber** [comment]
@STaRDoGG thanks!

I got some problems when pulling the image.

I ran: `docker pull docker.io/jscottelblein/llc-docker:latest`

And I got this as the output:

`Error response from daemon: pull access denied for jscottelblein/llc-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by STaRDoGG** [comment]
Oops, my bad. Try now:

    jscottelblein/llc-docker:latest

First time actually pushing an image anywhere. :p

**Comment by JulianPrieber** [comment]
I still can't pull the image.
I'm assuming this is the repo that contains all your changes: https://github.com/STaRDoGG/llc-docker.

I built an image from that and tested that.
Everything appears to work fine!

**From my point of view, all is looking good, and we are ready to merge.**

Thank you for your efforts!

**Comment by STaRDoGG** [comment]
> I still can't pull the image. I'm assuming this is the repo that contains all your changes: https://github.com/STaRDoGG/llc-docker.

Weird, everything seems to have gone ok on my end, and it wound up here: https://hub.docker.com/r/jscottelblein/llc-docker/tags

I have added 1 small tweak to the entrypoint since last pushing to my repo that I just want to test locally, and then I'll send the PR after. :)
